%YAML 1.1
---
- name: Roll a new random password over all Huawei network elements
  hosts: huaweis

  tasks:
  - name: Generate new passwords for each network element independently
    ansible.builtin.set_fact:
      password: "{{ lookup('ansible.builtin.password', '/dev/null') }}"

  - name: Store new password in Vault
    community.hashi_vault.vault_write:
      path: microwave_ne/data/{{ inventory_hostname }}
      url: http://172.20.189.237:8200/
      data:
        data:
          password: "{{ password }}"

  - name: Change password (on description field of ETH-14-255-2)
    ansible.netcommon.netconf_config:
      target: running
      content:
        config:
          "@xmlns": "urn:ietf:params:xml:ns:netconf:base:1.0"
          interfaces:
            "@xmlns": "urn:ietf:params:xml:ns:yang:ietf-interfaces"
            interface:
              name: ETH-14-255-2
              description: The password is {{ password }}
...
